apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: object-detection-deployment
spec:
  selector:
    matchLabels:
      app: object-detection
  replicas: 4
  template:
    metadata:
      labels:
        app: object-detection
    spec:
      containers:
      - name: object-detection
        image: anupamashipurkar/my-flask-app:v16
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "512Mi"
            cpu: "0.5"

