apiVersion: v1 
kind: Service
metadata:
  name: object-detection-service
spec:
  type: LoadBalancer
  selector:
    app: object-detection
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000